### ISSUE TITLE
Backups not uploading

### ISSUE THREAD

**Issue by tungmeister** [samccauley/addon-hassiogooglebackup#27]
I've just noticed that I've not had a backup upload since the end of August. I've just manually called the backup command and the latest snapshot still didn't upload. Here's the log:

`WARNING:django.request:Not Found: /favicon.ico
INFO:oauth2client.client:Refreshing access_token
INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
INFO:oauth2client.client:Refreshing access_token
WARNING:googleapiclient._helpers:build() takes at most 2 positional arguments (3 given)
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/drive/v3/files?q=name%3D%275894cad6.tar%27+and+%271vrpN11Wmkd0Nwu4UnjrsOL762mLOydZ7%27+in+parents+and+trashed+%3D+false&spaces=drive&fields=files%28id%2C+name%29&alt=json
INFO:root:Backing up /backup/5894cad6.tar to 1vrpN11Wmkd0Nwu4UnjrsOL762mLOydZ7
INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/upload/drive/v3/files?alt=json&uploadType=resumable
[2019-09-07 12:27:52 +0100] [16] [CRITICAL] WORKER TIMEOUT (pid:21)
gb_debug = false
Setting up normal logging
[2019-09-07 11:27:52 +0000] [21] [INFO] Worker exiting (pid: 21)
[2019-09-07 12:27:52 +0100] [22] [INFO] Booting worker with pid: 22
INFO:root:No local_settings to import`

**Comment by samccauley** [comment]
I'm taking a look at this now. Did you upgrade to 1.7.0 when it came out on August 29th? I suspect something I added in that release.

**Comment by samccauley** [comment]
@tungmeister Try version 1.7.1. That should fix the problem. Please let me know.

**Comment by mammuth** [comment]
I also noticed missing uploaded backups for a couple of weeks. 

However in my case I simply had no valid authorization anymore as it appears. 

What could have caused this? I think I also did a snapshot restore within that timeframe.

I think, it'd be really useful to have an home assistant integration with sensors for the last successful / failed upload. This way users could create an alert when there hasn't been a successfully uploaded backup for a couple of days. 

Relying on having backups and then noticing you have none if you need them should be avoidable.

**Comment by mammuth** [comment]
> @tungmeister Try version 1.7.1. That should fix the problem. Please let me know.

`CRITICAL WORKER TIMEOUT` still occures in version 1.7.1 I'm afraid.

```
DEBUG:root:backup fromPattern: /backup/*.tar
DEBUG:root:backup backupDirID: 1Q0VZyc5cpcLHo7X7cIhk-kA2GG8sEE
DEBUG:root:backup user_agent: http://192.168.178.46:8055/
INFO:oauth2client.client:Refreshing access_token
INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
INFO:oauth2client.client:Refreshing access_token
WARNING:googleapiclient._helpers:build() takes at most 2 positional arguments (3 given)
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/drive/v3/files?q=name%3D%27c19076e0.tar%27+and+%271Q0VZyc5cpHo7X7cIhk-WvkA28sEE%27+in+parents+and+trashed+%3D+false&spaces=drive&fields=files%28id%2C+name%29&alt=json
INFO:root:Backing up /backup/c19076e0.tar to 1Q0VZyc5cpHo7X7cIhk-WvkA2GG8sEE
DEBUG:root:drive_service = <googleapiclient.discovery.Resource object at 0x74c93c30>
DEBUG:root:MIMETYPE = application/tar
DEBUG:root:TITLE = Hassio Snapshot
DEBUG:root:DESCRIPTION = Hassio Snapshot backup copy
DEBUG:root:media_body: <googleapiclient.http.MediaFileUpload object at 0x74cca9b0>
INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/upload/drive/v3/files?alt=json&uploadType=resumable
[2019-11-02 11:31:06 +0100] [18] [CRITICAL] WORKER TIMEOUT (pid:41)
[2019-11-02 10:31:10 +0000] [41] [INFO] Worker exiting (pid: 41)
[2019-11-02 11:31:19 +0100] [43] [INFO] Booting worker with pid: 43
INFO:root:No local_settings to import
```

**Comment by apop880** [comment]
I'm seeing the same thing happen recently. Haven't had a snapshot upload successfully since June 7. I am on the latest version.
